### ISSUE TITLE
MVP Code Review: Albums

### ISSUE THREAD

**Issue by GreenRabite** [GreenRabite/captr#4]
David,

Please take a look at my Albums. Albums have basic CRUD functionality.

- [X] Registered users can create their own albums
- [X] Users can add photos to albums
- [X] Users can delete their own albums
- [X] Users can edit their own albums
- [X] Users can not add/delete/ or edit other people albums
- [ ] Users can see errors if an issue occurs
- [x] Users will be redirect to PhotosIndex if an album is deleted
- [x] Users will be redirect to PhotosShow if a picture is added
- [x] Users will be redirect to PhotosIndex if an album is deleted
- [x] Users will be redirect to AlbumShow if an album is edited
- [x] Users will not be able to see the edit/delete button if they are not the owners.

**Comment by dobrynin** [comment]
I'm running into some bugs when trying to create an album.

**Comment by GreenRabite** [comment]
Update some issues that arose when playing with the "Submit" button CSS. Added some other functionality to the submit button.
