### ISSUE TITLE
MVP Code Review: Comments

### ISSUE THREAD

**Issue by GreenRabite** [GreenRabite/captr#5]
David,

Please take a look at my comments on the PhotoShow page for functionality. Registered users can post comment on anybody's PhotoShow page. Users can only delete their comment. Users cannot delete other users comments.

- [X] PhotoShow page have Comments that can either be deleted or create by users
- [x] Users can only delete their own comment
- [x] Users can add a comment to any Photo show page
- [x] User will get an error if they try to delete a comment they don't own

**Comment by dobrynin** [comment]
You should not display an "X" at all if a comment does not belong to the current user.
